### ISSUE TITLE
Odoo is not running on clean run

### ISSUE THREAD

**Issue by AzizMarashly** [kmagusiak/odoo-vscode#6]
I just cloned the repo and ran the dev container, but when I enter port 8069, nothing shows up. However, if I manually run the command `odoo-bin—-dev xml', then everything is running okay.

**Steps to Reproduce:**
1. Clone the repository.
2. Run the dev container.
3. Try accessing port 8069.

**Expected Behavior:**
After running the dev container, accessing port 8069 should display the Odoo login page.

**Actual Behavior:**
No content is displayed when accessing port 8069 after running the dev container.

**Additional Information:**
Manually running the command `odoo-bin --dev xml` results in everything running as expected.

**Comment by kmagusiak** [comment]
This is the expected behavior for devcontainers, because you want the devcontainer to start regardless of starting the service. Once the devcontainer is running, you can run multiple time (and with different arguments) Odoo; for example use `F5` to start with the debugger. To reflect most code changes, you may need to restart Odoo and you do not want to restart the devcontainer itself.
